# Site settings
title: "TK Resume"
description: "TK Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    Tetiana Kolotusha
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "tani.kolotusha@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+44 7365 863338"
resume_contact_address:         "London"

resume_header_contact_info:     "London • +44 7365 863338 • tani.kolotusha@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I received a BA in Cultural Studies from Kyiv-Mohyla Academy in Kyiv, Ukraine, and an MA in History of Art from Charles
University in Prague, Czech Republic. Fluent in three languages - English, Czech, Ukrainian. Skilled B2B sales executive with a customer centric approach. In my previous roles, I gained experience in the full sales cycle from prospecting to successfully closing deals. I’m a target-driven salesperson with an entrepreneurial spirit. My perspective in life and career is to always look for an opportunity to perfect my approach and the product delivered. I’m a strategic thinker with a growth mindset.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "https://www.facebook.com/tanya.kolotusha"
  resume_linkedin_url:          "https://www.linkedin.com/in/tanya-kolotusha-008366172/"
  resume_instagram_url:         "https://www.instagram.com/tanya_kolotusha/"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
