# Site settings
title: "TK Resume"
description: "TK Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    Tetiana Kolotusha
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "tani.kolotusha@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+44 7365 863338"
resume_contact_address:         "London"

resume_header_contact_info:     "London • +44 7365 863338 • tani.kolotusha@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>My Bachelor's degree left me feeling like I have received an excellent theoretical humanitarian education, but I had no idea what to do with it. I was craving new experiences and knowledge. Having an adventurous spirit, I have always dreamed of traveling and living abroad. I made a decision and moved to Prague, Czech Republic. After 5 months of learning the Czech language, I was accepted to Masarikov and Charles University, choosing the latter one.  Masters in History of Art was not a practical decision I thought I was making. Studying was interesting, but my passion for writing, theory, and politics was not satisfied. Subsequently, I`ve attempted to combine my interests with the degree. The result is reflected in my Master thesis “Art during the revolution in Ukraine 2013 - 2014”. The main focus of my thesis is interviews conducted by me with artists who were active during the revolution in Kyiv, both professionally and as protesters. 
I look forward to working in a company with a fast-paced environment, where people value quality over quantity.  I see myself amongst strong, smart, and tolerant people, who inspire each other to be better.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "https://www.facebook.com/tanya.kolotusha"
  resume_linkedin_url:          "https://www.linkedin.com/in/tanya-kolotusha-008366172/"
  resume_instagram_url:         "https://www.instagram.com/tanya_kolotusha/"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
